# Generated by Django 2.2.3 on 2019-07-30 04:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('tv_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('complete', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(default=datetime.datetime.now)),
                ('post_dates', models.CharField(max_length=255)),
                ('quantity_symbols', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity_days', models.PositiveIntegerField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('reception', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='table.Choice')),
            ],
        ),
    ]
