# Generated by Django 2.2.5 on 2019-09-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Каналы', 'verbose_name_plural': 'Каналы'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Обьявления', 'verbose_name_plural': 'Обьявления'},
        ),
    ]
